[package]
name = "thunder"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.4.2"
etherparse = "0.14.2"
tun-tap = "0.1.4"

[lib]
name = "thunder"

[[bin]]
name = "thunder"
